### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by Cutuchiqueno** [niklasl/vim-rdf#2]
When I hit `:RDF` I always get the following error message:

    Traceback (most recent call last):
      File "<string>", line 9, in <module>
      File "/home/cutuchiqueno/.vim/plugged/vim-rdf/pythonx/rdfns.py", line 48, in __init__
        self.prefixes = PrefixCache(os.path.join(basedir, 'prefixes.ttl'))
      File "/usr/lib/python2.7/posixpath.py", line 70, in join
        elif path == '' or path.endswith('/'):
    AttributeError: 'NoneType' object has no attribute 'endswith'

**Comment by niklasl** [comment]
Thanks for the report! That happens because the plugin cannot find any directory to read and write vocabularies in. The candidates are (from https://github.com/niklasl/vim-rdf/blob/master/pythonx/rdfns.py#L11):

* $RDF_VOCAB_CACHE environment variable if given
* ~/rdf-vocab-cache
* ~/Documents/rdf-vocab-cache
* /usr/local/share/rdf-vocab-cache

Create any of those and things should work.

**Comment by niklasl** [comment]
I'll keep this issue open since I need to improve the error handling and documentation.

Also, the list of candidates could use an overhaul. For one I should probably add an `$XDG_CONFIG_HOME` (`~/.config` option.) The plugin should probably recommend that location, and create a directory there if missing.

**Comment by Cutuchiqueno** [comment]
Thanks for answering.

I set $RDF_VOCAB_CACHE to $HOME/.vim-rdf-cace before but this does not have seemed to work

Using /usr/loacl/share/rdf-vocab-cache works now. A cahce file is created and there is no error message anymore

However - different problem but not sure if I should really open another issue for that - vim now says omnifunc is not set although from my understanding of the comments in the code this should had happened by using the `:RDF` command. Additionally I am not quiet sure to what name I can use to set omnicompletion myself.

Thanks

**Comment by niklasl** [comment]
I see; I'll investigate that too. (AFAIK though, depending on how you run Vim, certain environment options might not carry over as expected.)

Ah, the `:RDF` command sets up *user-defined* completion, i.e. using CTRL-X_CTRL-U. (See `:help compl-function`.) Instead of calling `:RDF` to set that up, you can wire things to your liking (in an ftplugin), e.g. to `omnifunc`:

    setlocal omnifunc=rdfnscomplete#complete

Eventually, this plugin might be adapted to syntax specific forms and set this up. But since it currently doesn't do full syntax completion, only the RDF prefix stuff, I prefer to have it unobtrusive like this.

**Comment by Cutuchiqueno** [comment]
Both `CTRL-X_CTRL-U` and `CTRL-X_CTRL-O` set up manually by setting the omnifunc variable as you have described result in a `pattern not found` message.

I imported foaf and tested for completion of `Agent`

    @prefix foaf: <http://xmlns.com/foaf/spec/> .

    foaf:Ag

I assured that the foaf file was cached in the dirctory given by $RDF_VOCAB_CAHCHE

**Comment by niklasl** [comment]
Ah, I believe the `foaf` prefix is bound to the wrong IRI in your example. It should be:

    @prefix foaf: <http://xmlns.com/foaf/0.1/> .

(You should be able to complete prefixes as well. The plugin will look up uncached prefixes using http://prefix.cc/. You can also add/remove them by editing $RDF_VOCAB_CAHCHE/prefixes.ttl and run `:RDF reload`.)

**Comment by Cutuchiqueno** [comment]
ok, having used the wrong namespace is kind of embarrissing. Thank you for your intensive support. Everything works well now.

**Comment by niklasl** [comment]
No problem, I'm happy to help and glad you're using the plugin!
